name: Deploy main branch
run-name: ${{ github.actor }} is deploying ${{ github.repository }} main branch
on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    name: Lint, test, build, and deploy
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-west-2

      - name: Setup Node.js environment
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Cache node_modules
        uses: actions/cache@v3
        id: yarn-cache
        with:
          path: ${{ steps.yarn-cache-dir-path.outputs.dir }}
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-

      - name: Lint, test, build react application
        run: |
          yarn install --frozen-lockfile || yarn install
          yarn lint
        working-directory: ./frontend

      - name: Deploy to AWS using Pulumi script
        uses: pulumi/actions@v3
        with:
          command: up
          stack-name: prod
          refresh: true
          working-directory: ./deploy
        env:
          PULUMI_ACCESS_TOKEN: ${{ secrets.PULUMI_ACCESS_TOKEN }}
