name: Deploy main branch
run-name: ${{ github.actor }} is deploying ${{ github.repository }} main branch
on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    name: Lint, test, build, and deploy
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1-node16
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-west-2

      - name: Setup Node.js environment
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Get yarn cache directory path
        id: yarn-cache-dir-path
        run: echo "YARN_CACHE_DIR=$(yarn cache dir)" >> $GITHUB_ENV

      - name: Enable cache
        uses: actions/cache@v3
        id: yarn-cache
        with:
          path: echo "${{env.YARN_CACHE_DIR}}"
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-

      - name: Lint, test, build react application
        run: |
          yarn install --frozen-lockfile || yarn install
          yarn lint
        working-directory: ./frontend

      - name: Install Pulumi CLI
        uses: pulumi/setup-pulumi@v2

      - name: Deploy to AWS using Pulumi script
        uses: pulumi/actions@v3.2.0
        with:
          command: up
          stack-name: prod
          refresh: true
          work-dir: ./deploy
        env:
          PULUMI_ACCESS_TOKEN: ${{ secrets.PULUMI_ACCESS_TOKEN }}
